### PR TITLE
switch GCR -> Artifact-Registry

### PR DESCRIPTION
**Pull request by ccwienk**
GCR has been deprecated [0] in favour of Artifact-Registry.

Thus, change push-targets for OCI-Images:

- europe-docker.pkg.dev/gardener-project/snapshots for snapshots
- europe-docker.pkg.dev/gardener-project/releases for releases
- europe-docker.pkg.dev/gardener-project/public for combined view of snapshots + releases

[0]
https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr

**Release note**:

```breaking operator
Change OCI Image Registry from GCR (`eu.gcr.io/gardener-project`) to Artifact-Registry (`europe-docker.pkg.dev/gardener-project/releases`). Users should update their references.

```

### CODE REVIEW

**Comment by ccwienk** [comment]
@BeckerMax  | @kon-angelo : I think the last upgrade of golang-version broke the build:

[buildlog](https://concourse.ci.gardener.cloud/teams/gardener/pipelines/aws-lb-readvertiser-master/jobs/master-head-update-job/builds/2)
[pull-request](https://github.com/gardener/aws-lb-readvertiser/pull/26)

So while I think this issue is most likely not related to _this_ pull-request, I still think it should be resolved, wdyt?

**Comment by kon-angelo** [comment]
We will proceed to deprecate this repo shortly. We can close this PR

**Comment by ccwienk** [comment]
> We will proceed to deprecate this repo shortly. We can close this PR

😑

**Comment by ccwienk** [comment]
as discussed, merging the pull-request (even though the repository will be archived soon-ish)

**Pull request merged**
